service: serverless-parameter-store
frameworkVersion: '3'


custom:
  settings:
    USER_ID: ${ssm:USER_ID}
    PASSWORD: ${ssm:PASSWORD}

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-south-1
  environment: ${self:custom.settings}

functions:
  getssm:
    handler: handler.getssm
    events:
      - http:
          method: get
          path: parameter    

#aws ssm put-parameter --name USER_ID --value shruti --type String
#aws ssm put-parameter --name PASSWORD --value shruti123 --type String